using System.Collections.Generic;

public class VersionInfo
{
    public string abc { get; set; }
    public int assessor_max_cases_in_task { get; set; }
    public int assessor_overlap { get; set; }
    public int black_list_id { get; set; }
    public int booking_id { get; set; }
    public BookingInfo booking_info { get; set; }
    public string booking_regular_id { get; set; }
    public List<object> case_attributes_to_show { get; set; }
    public bool case_info_required { get; set; }
    public List<object> case_properties_to_show { get; set; }
    public List<string> check_ticket_tags { get; set; }
    public string check_ticket_tags_explanation { get; set; }
    public bool check_ticket_tags_free_input { get; set; }
    public int check_ticket_tags_max_limit { get; set; }
    public int check_ticket_tags_min_limit { get; set; }
    public string coherence_uuid { get; set; }
    public CostInfo cost_info { get; set; }
    public List<object> country_filter { get; set; }
    public string current_max_quota { get; set; }
    public bool doNotCommentOpenBugs { get; set; }
    public double graph_build_version { get; set; }
    public int initial_assessor_cost { get; set; }
    public List<string> instruction { get; set; }
    public List<string> interested_people { get; set; }
    public bool is_all_bugs_check_required { get; set; }
    public bool is_blocked_cases_check_required { get; set; }
    public bool is_broken_cases_check_required { get; set; }
    public bool is_check_required { get; set; }
    public bool is_correctness_check_required { get; set; }
    public bool is_deadline_assured { get; set; }
    public bool is_deadline_notifications_required { get; set; }
    public bool is_duplicate_check_required { get; set; }
    public bool is_dynamic_deadline_required { get; set; }
    public bool is_failed_cases_check_required { get; set; }
    public bool is_hotfix { get; set; }
    public bool is_improvements_check_required { get; set; }
    public bool is_knownbug_cases_check_required { get; set; }
    public bool is_missed_bugs_check_required { get; set; }
    public bool is_need_to_set_ticket_params_for_old_bugs { get; set; }
    public bool is_report_blocked_comments_required { get; set; }
    public bool is_report_broken_comments_required { get; set; }
    public bool is_report_case_timings_required { get; set; }
    public bool is_report_failed_comments_required { get; set; }
    public bool is_report_knownbug_comments_required { get; set; }
    public bool is_report_passed_comments_required { get; set; }
    public bool is_report_process_timings_required { get; set; }
    public bool is_report_required { get; set; }
    public bool is_report_set_tmp_params_required { get; set; }
    public bool is_report_show_cost_rub_required { get; set; }
    public bool is_report_skipped_comments_required { get; set; }
    public bool is_report_testrun_timings_required { get; set; }
    public bool is_report_verdicts_compare_required { get; set; }
    public bool is_report_write_to_ticket_required { get; set; }
    public bool is_reproducibility_message_required { get; set; }
    public bool is_silent_mode { get; set; }
    public bool is_skipped_cases_check_required { get; set; }
    public bool is_version_archive_required { get; set; }
    public int job_id { get; set; }
    public long job_start_ts { get; set; }
    public bool just_show_start_info { get; set; }
    public List<object> launch_tags { get; set; }
    public int limit_for_deadline_notifications { get; set; }
    public int limit_for_duplicate_check { get; set; }
    public int limit_for_missed_bugs_check { get; set; }
    public int limit_for_testrun_timings_report { get; set; }
    public string @namespace { get; set; }
    public string object_type { get; set; }
    public string parent_namespace { get; set; }
    public List<object> parent_ticket_summonees { get; set; }
    public string production_check_stend { get; set; }
    public string production_check_type { get; set; }
    public string project_name { get; set; }
    public QualitySettings quality_settings { get; set; }
    public string quota_month_size { get; set; }
    public string quota_skill_id { get; set; }
    public string quota_skill_name { get; set; }
    public string requester { get; set; }
    public string requester_code { get; set; }
    public string requester_code_explanation { get; set; }
    public string set_affected_version_in_main_queue_tickets { get; set; }
    public string set_parent_ticket_status { get; set; }
    public List<object> set_ticket_affected_versions { get; set; }
    public List<object> set_ticket_components { get; set; }
    public List<object> set_ticket_fix_versions { get; set; }
    public List<string> set_ticket_followers { get; set; }
    public List<object> set_ticket_reproduced_in { get; set; }
    public List<string> set_ticket_tags { get; set; }
    public string special_condition { get; set; }
    public string statistic_namespace { get; set; }
    public bool templateShowCaseDescription { get; set; }
    public bool templateShowCaseId { get; set; }
    public bool templateShowCasePrecondition { get; set; }
    public bool templateShowRunTags { get; set; }
    public bool templateShowRunTitle { get; set; }
    public bool templateShowSuiteTitle { get; set; }
    public string test_stend { get; set; }
    public List<object> testrun_ids { get; set; }
    public List<object> testrun_properties_to_show { get; set; }
    public string th_mode { get; set; }
    public int th_simultaneous_runs_limit { get; set; }
    public string tickets_queue { get; set; }
    public string tickets_workflow_type { get; set; }
    public List<object> toloka_instruction { get; set; }
    public List<object> toloker_hp_match_attributes { get; set; }
    public List<object> toloker_hp_match_keys { get; set; }
    public int toloker_max_cases_in_task { get; set; }
    public int toloker_overlap { get; set; }
    public string version { get; set; }
    public string version_id { get; set; }
    public string version_uuid { get; set; }
    public string workers_scope { get; set; }
    public string workers_scope_errors_handler { get; set; }
}
